name = "Ian The Designer"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'pages', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.54.0"

[author]
  name = "Ian Donahue"
  homepage = "https://ianthedesigner.com/"

[original]
  name = "Ian Donahue"
  homepage = "https://ianthedesigner.com/"
